### ISSUE TITLE
When there is a problem with the JSON file reading, the error message is displayed as Unable to read CSV data to %s. Check provided path."

### ISSUE THREAD

**Issue by amuthansakthivel** [sskorol/test-data-supplier#104]
[//]: # (
. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

### I'm submitting 
 - bug report
 
### Environment

| Test Data Supplier | 1.7.0 |
| TestNG | 6.14.3 |
| Build tool | Maven |
| IDE | IntelliJ@2021.3 |

### Is the issue reproducible on a runner?
Yes

### What is the expected behavior?

When the user enters incorrect path of json file, the error message should indicate "Unable to read json data. "

### What is the actual behavior?
The error message is "Unable to read csv data"

### Other information 
[//]: # (
Issue is in the JsonReader.class at line number 61

 throw new IllegalArgumentException(String.format("Unable to read CSV data to %s. Check provided path.", this.entityClass), var23);
)

**Comment by sskorol** [comment]
@amuthansakthivel thanks for the report!
