### ISSUE TITLE
Request to add Excel Parser to Test Data Supplier

### ISSUE THREAD

**Issue by amuthansakthivel** [sskorol/test-data-supplier#105]
### I'm submitting 
 - [ ] feature request
 
### Environment

| Test Data Supplier | 1.7.0 |
| --- | --- |
| TestNG | 7.4.0 |

### What is the expected behavior?
Most of the test automation were still driven by Excel sheet. It would be great if test data supplier can extend the parser mechanism to support Excel Sheet. It can be done easily with the help of Zerocell library.

https://github.com/creditdatamw/zerocell

I have also made an youtube video on that library - https://www.youtube.com/watch?v=Itzkk5Nx6Uo&t=20s

### What is the actual behavior?
Currently test-data-supplier does not support Excel parsing

### What is the motivation / use case for changing the behavior?
Most of the test automation engineers are still using the excel sheet to drive their tests.
I am planning to make a video in my youtube channel about test-data-supplier. Libraries like this needs the pedestal it deserve.

### Other information 
Zerocell is excellent library to convert excel data to POJO using annotations. Test data supplier can simply leverage this library to provide a new Excel Parser class.

**Comment by sskorol** [comment]
@amuthansakthivel thanks, will take a look after holidays.

**Comment by sskorol** [comment]
@amuthansakthivel I checked zerocell lib. It internally uses apache poi which currently [doesn't support Java modules yet](https://poi.apache.org/help/faq.html#faq-N102B0). So it won't compile with modular DataSupplier unfortunately. I'll check the other excel-reader options on the market.

**Comment by amuthansakthivel** [comment]
Thanks a lot Sergey Korol. I have created a video on test-data-supplier in
youtube and shared in social media like telegram and linkedin connections.

Hopefully many people would start to use this amazing library soon.

https://www.youtube.com/watch?v=mu0c0YZoRxM

https://www.linkedin.com/posts/amuthan-sakthivel-528b89107_testing-testingminibytes-java-activity-6883784189376888834-_dnR

Thanks for all your contribution to the community!

**Comment by sskorol** [comment]
@amuthansakthivel thanks for sharing! Really appreciate it!

BTW, I've just checked the latest poi version. It seems like they added automatic modules into 5.1.0 version. Will debug zerocell with 5.10. But I believe it should work. So if zerocell's author releases a new version with an updated poi soon, it'll give me a green light to update DataSupplier as well.

**Comment by amuthansakthivel** [comment]
Wow that's a good news for sure

**Comment by sskorol** [comment]
@amuthansakthivel just a quick update: poi update is already merged into ZeroCell main branch. I've also pushed changes to support excel files processing in DadaSupplier. So as soon as @zikani03 creates a new release, I can merge my changes and do the same with DS.

**Comment by sskorol** [comment]
A new ZeroCell version was released, so I'll prepare TestDataSupplier release as well.

**Comment by sskorol** [comment]
Just released a new version 1.9.7. Should be available as soon as it appears here: https://repo1.maven.org/maven2/io/github/sskorol/test-data-supplier/
It may take more time until it appears in Maven search results though.

**Comment by amuthansakthivel** [comment]
Wow this is great news. You are awesome!!
