### ISSUE TITLE
Unable to add the dependency in pom.xml

### ISSUE THREAD

**Issue by Renjith-H** [sskorol/test-data-supplier#160]
Hi Team,

I am unable to add 'test-data-supplier' dependency to pom.xml file in my Maven project.
I am using Java 1.8, TestNG 7.4 in my project.
I have tried with all the versions of test-data-supplier but it doesn't work.

Error:
Dependency 'io.github.sskorol:test-data-supplier:2.1.0' not found

Scrrenshot:
![image](https://user-images.githubusercontent.com/87613429/207661759-bbbb1e21-5a0f-4c20-97e2-43cb2eb273c7.png)

**Comment by sskorol** [comment]
According to the official [maven repo](https://repo1.maven.org/maven2/io/github/sskorol/test-data-supplier/), it's there.
Please share your `pom.xml`.

**Comment by Renjith-H** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>SeleniumFramework</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>SeleniumFramework</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-server</artifactId>
      <version>3.141.59</version>
    </dependency>
    
    <dependency>
      <groupId>io.github.bonigarcia</groupId>
      <artifactId>webdrivermanager</artifactId>
      <version>5.0.3</version>
    </dependency>

    
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>7.4.0</version>
    </dependency>
    
    <dependency>
      <groupId>com.aventstack</groupId>
      <artifactId>extentreports</artifactId>
      <version>5.0.5</version>
    </dependency>
    
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>4.1.2</version>
    </dependency>
    
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>4.1.2</version>
    </dependency>
    
    <dependency>
      <groupId>org.aeonbits.owner</groupId>
      <artifactId>owner</artifactId>
      <version>1.0.12</version>
    </dependency>

    <dependency>
      <groupId>io.github.sskorol</groupId>
      <artifactId>test-data-supplier</artifactId>
      <version>2.1.0</version>
    </dependency>
  </dependencies>
</project>

**Comment by sskorol** [comment]
I apologizes for the late reply. Did you solve your issue?
Also note that you can't use latest DataSupplier with Java 8. It requires Java 17 since 2.0.0. See README installation sections for different Java versions.

**Comment by sskorol** [comment]
Feel free to reopen, if the problem is still in place.
