### ISSUE TITLE
Providing the ability to retrieve data at runtime from several spreadsheets in an Excel file wherein each sheet had the same structure.

### ISSUE THREAD

**Issue by saiprakashpudi** [sskorol/test-data-supplier#197]
[//]: # (
. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

### Description
[//]: # (
. Describe your problem in several sentences to give context.
)
ToDo
### Issue Type 
 - [ ] bug report
 - [x] feature request
 
### Environment

| Component          | Version           |
|--------------------|-------------------|
| Test Data Supplier | 2.2.0             |
| TestNG             | 7.7.1             |
| Build tool         | gradle@7.6.0      |
| IDE                | IntelliJ@2022.2.3 |
| JDK                | temurin-17.0.6    |

### Can be reproduced via

- [ ] Bash
- [ ] Maven
- [ ] Gradle
- [ ] Eclipse
- [ ] IntelliJ

### Expected behavior
[//]: # (
. Describe your vision on this issue.
)
ToDo

### Actual behavior
[//]: # (
. If the current behavior is a bug, please provide the steps to reproduce an issue. And if possible, a minimal demo of the problem.
)
ToDo

### What's the motivation for changing the current behavior?
[//]: # (
. Clarify your use case.
)
ToDo

### Additional information 
[//]: # (
. Detailed explanation, stacktrace, related issues, suggestions on 
. how to fix, links for us to understand a context, e.g. Stackoverflow
)
ToDo

**Comment by sskorol** [comment]
@saiprakashpudi check 2.3.0 version as soon as it's available in maven central. It usually takes a couple of hours.
