### ISSUE TITLE
Java 9 support - illegal reflective access issue due to joor

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [sskorol/test-data-supplier#70]
While this issue is due to joor, I'd like to make it general for test-data-supplier to support JDK9.

Even if you won't be able to tackle it (for any reasons at all) I'd still want to thank you for creating this. :-)

#### I'm submitting 
 - [ ] bug report
 - [x] feature request
 
#### Environment

| Test Data Supplier | 1.7.0 |
| --- | --- |
| TestNG | 6.14.3 |
| Build tool | Maven 3.5 |
| IDE | IntelliJ@2018.1.5 |

#### Is the issue reproductible on runner?

- [x] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

#### What is the expected behavior?
No JDK9-related warnings.

#### What is the actual behavior?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.joor.Reflect (file:/home/tammo/.m2/repository/org/jooq/joor-java-8/0.9.8/joor-java-8-0.9.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.joor.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```
#### What is the motivation / use case for changing the behavior?

JDK11 is just around the corner. JUnit 5 becomes an alternative for my beloved TestNG. :-) We can't have that! 

Let me know if you'd like me to provide any details on, e.g., how I got the issue.

**Comment by sskorol** [comment]
@LIttleAncientForestKami thanks for reporting, I'll check what I can do with it.

**Comment by sskorol** [comment]
@LIttleAncientForestKami just checked on Java 9. Seems like it's just a warning, which shouldn't affect execution itself. At least I can see `DataSupplier` working as expected. Regarding JOOR, it has several releases built for different Java versions. And the one which purely works with Java 9, requires project to be built with Java 9 as well. I have a general concern that Java 9 is almost dead for lots of people. And others who still sit on Java 8, will jump directly to Java 11 I believe. I'd plan moving this direction and schedule a general update to Java 11, rather than creating small releases for dead versions. Does it make sense?

**Comment by LIttleAncientForestKami** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Sure! By Java 9 support I meant modular Java. Cause this is a warning now and won't execute later. I'm fine with clearly stated target JDK 11. Freely renomę the issue or open a milestone or what suits better.                                                                                                                                                                        z tel., litości                                                                                                                                                                           Od: notifications@github.comWysłano: 29 sierpnia 2018 5:59 PMDo: test-data-supplier@noreply.github.comOdp. do: reply@reply.github.comDW: Tomasz.Borek@gmail.com; mention@noreply.github.comTemat: Re: [sskorol/test-data-supplier] Java 9 support - illegal reflective access issue due to joor (#70)  @LIttleAncientForestKami just checked on Java 9. Seems like it's just a warning, which shouldn't affect execution itself. At least I can see DataSupplier working as expected. Regarding JOOR, it has several releases built for different Java versions. And the one which purely works with Java 9, requires project to be built with Java 9 as well. I have a general concern that Java 9 is almost dead for lots of people. And others who still sit on Java 8, will jump directly to Java 11 I believe. I'd plan moving this direction and schedule a general update to Java 11, rather than creating small releases for dead versions. Does it make sense?

**Comment by sskorol** [comment]
@LIttleAncientForestKami you can test it on Java 10. As soon as AspectJ is updated to support Java 11, I'll migrate to the latest version as well.
