### ISSUE TITLE
Is support separate @DataSupplier and @Test into different Java class?

### ISSUE THREAD

**Issue by ansonliao** [sskorol/test-data-supplier#75]
Is support separate `@DataSupplier` and `@Test` into different Java class?

**Comment by sskorol** [comment]
@ansonliao yes, you can use similar to common DataProvider syntax:

`@Test(dataProviderClass = ExternalDataSuppliers.class, dataProvider = "getCommonData")`

see https://github.com/sskorol/test-data-supplier/blob/master/src/test/java/io/github/sskorol/datasuppliers/ExternalDataSuppliers.java#L54 and https://github.com/sskorol/test-data-supplier/blob/master/src/test/java/io/github/sskorol/testcases/CommonDataProviderTests.java#L27

**Comment by ansonliao** [comment]
Thanks @sskorol replied.
But from the sample, it is the TestNG built-in feature, it isn't `@DataSupplier`

**Comment by sskorol** [comment]
@ansonliao do you really think that I'd give you fake info, being a library owner?.. ;) read the documentation carefully please... it lists all the features, including those that you asked for... moreover, I believe it's worth for you try to what I suggested... miracles happen :)

**Comment by ansonliao** [comment]
@sskorol 
Thanks for your reply, let me study this library deeply.
