### ISSUE TITLE
Parameters in DataSupplier ?

### ISSUE THREAD

**Issue by longk15t** [sskorol/test-data-supplier#78]
[//]: # (
. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

#### I'm submitting 
 - [ ] bug report
 - [ ] feature request
 - [x] question
 
#### Content

Can we pass parameters in @DataSupplier ? sth like this

@DataSupplier
public Stream<Object> foo(String param1, int param2){
    //return sth
}

@Test(dataProvider = "foo", dataProviderParams = "stringA;5")
public void testFoo(Object bar) {
    //test code here
}

**Comment by MikeShysh** [comment]
Hi, 
Why do you need this? Maybe check Factory feature for testng https://testng.org/doc/documentation-main.html#factories

**Comment by sskorol** [comment]
@longk15t can you describe your use case in details?.. what are you trying to achieve by passing parameters into a method which is intentionally designed to pass parameters (as return values) to test cases?

**Comment by sskorol** [comment]
@longk15t feel free to reopen it in case of any new details
