### ISSUE TITLE
IntelliJ Idea 2019.3 compatability

### ISSUE THREAD

**Issue by magnus80** [sskorol/test-data-supplier#85]
How to use test data supplier with IntelliJ Idea 2019.3?

**Comment by sskorol** [comment]
@magnus80 haven't yet updated it to *.3 version. Thanks for notification. Will do it. It should be available in couple of days after publishing and moderating.

**Comment by sskorol** [comment]
@magnus80 however, I can see it's already approved. So you can try to check the updates.
