### ISSUE TITLE
IntelliJ Idea 2020 compatability

### ISSUE THREAD

**Issue by magnus80** [sskorol/test-data-supplier#88]
[//]: # (
. Note: for support questions, please use Stackoverflow. 
. This repository is for feature requests and bug reports only.
.
. Make sure you have a clear name for your issue. An example of good issue names:
.
. - NPE occurs while using DS with class level Test annotation
. - Add an ability to use DS with Factory annotation
. - External data sources support
)

#### I'm submitting 
 - [ ] bug report
 - [ ] feature request
 
#### Environment

| Test Data Supplier | 1.7.0 |
| --- | --- |
| TestNG | 7.0.0 |
| Build tool | gradle@6.2.2 |
| IDE | IntelliJ@2020.1|

#### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

#### What is the expected behavior?
[//]: # (
. Add IntelliJ Idea 2020 compatability
)

**Comment by sskorol** [comment]
Submitted a new version for review. Should be available within 2 days.

**Comment by sskorol** [comment]
Already available.
